# Generated by Django 5.2 on 2025-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parking", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parkinglot",
            name="total_entry_gate",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="ticket",
            name="entry_gate",
            field=models.IntegerField(default=0),
        ),
    ]
