# Generated by Django 5.2 on 2025-05-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike')], max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
